### ISSUE TITLE
Create a installation howto

### ISSUE THREAD

**Issue by froscon2024** [fossasia/badgemagic-firmware#51]
The general user would have of course the most simple question at the moment: How can i install the released FOSS firmware on the badge?
This question should be answered on the main page. https://github.com/fossasia/badgemagic-firmware

At the moment its completely unanswered. I had to dig into the issues to get out of this issue report what have to be done now: https://github.com/fossasia/badgemagic-firmware/issues/38

This repo at the same time did not tell what software to use to install the foss firmware. I had to search around in other repo to find some hints: https://github.com/fossasia/badgemagic-hardware?tab=readme-ov-file#platform

So it seem to be https://github.com/ch32-rs/wchisp

At the moment its currently not listed here: https://github.com/ch32-rs/wchisp?tab=readme-ov-file#tested-on
I plan to make a PR at https://github.com/ch32-rs/wchisp?tab=readme-ov-file#tested-on when i tested it myself.

**Comment by kienvo** [comment]
It's funny that I just thought the flashing guide had been already on this repo. Turns out that just a [bootloader description](https://github.com/fossasia/badgemagic-firmware/blob/master/CH582.md#bootloader)

For flashing software, yes, it is `wchisp`. After installing `wchisp` and entering the bootloader, just run `make isp`. It will do the rest.

**Comment by froscon2024** [comment]
You released a .bin and a .elf file in version 0.1. Because of a missing howto, i just tried out the .bin and that seem to have worked.
The wchisp is capable of flashing both file types: https://github.com/ch32-rs/wchisp?tab=readme-ov-file#usage

**Comment by hpdang** [comment]
@froscon2024 are you at Froscon this weekend? We have a new prototype of the badge for you, please stop by our stand if you are around

**Comment by froscon2024** [comment]
> We have a new prototype of the badge for you

Picked it up. Thanks @hpdang 
I already told in person to @mariobehling about the misunderstanding that caused https://github.com/fossasia/badgemagic-hardware/issues/35
Some soldering to this prototype have been done last 2 days and pictures are upcoming to solve this misunderstanding as detailed as possible.
